server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kfc-rental.mysql.database.azure.com:3306/rentalCar?useSSL=true&requireSSL=false
    username: kfc@kfc-rental
    password: {password}
  jpa:
    show-sql: true
